version: "3"
services:
  server:
    depends_on:
      - redis
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    command: opentelemetry-instrument uvicorn main:app --log-level info --proxy-headers --host 0.0.0.0 --port 8000
    # command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    depends_on:
      - redis
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - OTEL_LOG_LEVEL="debug"
    command: celery -A tasks worker --loglevel=info --task-events --concurrency=1

  redis:
    image: redis
    ports:
    - "6379:6379"
